# Generated by Django 5.0.6 on 2024-12-15 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0002_remove_doctor_availabletime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.designation'),
        ),
    ]
