# Generated by Django 5.0.6 on 2024-12-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='descriptions',
            field=models.TextField(null=True),
        ),
    ]
